import {readFileSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../../../..');
const pin=JSON.parse(readFileSync(resolve(root,'src/XState/upstream.json'),'utf8'));
const {createActor,createMachine,fromCallback,log,enqueueActions,emit,assign,spawnChild,stopChild,raise,sendTo,sendParent,forwardTo,cancel}=await import(pathToFileURL(resolve(root,pin.sourceDirectory,'packages/core/src/index.ts')).href);
const native=JSON.parse(readFileSync(resolve(root,'tmp/xstate-parity/csharp-definitions.json'),'utf8'));
const actionType=action=>typeof action==='string'?action:typeof action==='function'?(action.type??action.name):action.type;
const action=action=>({type:action.type,hasParams:Object.hasOwn(action,'params'),parameters:typeof action.params==='function'?'function':action.params??null});
const transition=t=>({source:'#'+t.source.id,target:(t.target??[]).map(node=>'#'+node.id),eventType:t.eventType,reenter:t.reenter,hasTarget:t.target!==undefined,guard:t.guard!==undefined,actions:t.actions.map(actionType)});
const node=d=>({id:d.id,key:d.key,version:d.version??null,type:d.type,initial:transition(d.initial),history:d.history,order:d.order,states:Object.fromEntries(Object.entries(d.states).map(([key,value])=>[key,node(value)])),on:Object.fromEntries(Object.entries(d.on).map(([key,value])=>[key,value.map(transition)])),transitions:d.transitions.map(transition),entry:d.entry.map(action),exit:d.exit.map(action=>action.type),hasMeta:d.meta!==undefined,meta:d.meta??null,description:d.description??null,tags:d.tags,output:d.output!==undefined,invoke:d.invoke.map(inv=>({id:inv.id,src:inv.src,systemId:inv.systemId??null,input:inv.input!==undefined,done:Array.isArray(inv.onDone)?inv.onDone.length:inv.onDone?1:0,error:Array.isArray(inv.onError)?inv.onError.length:inv.onError?1:0,snapshot:inv.onSnapshot!==undefined}))});
it('provides invoke definitions',()=>{const machine=createMachine({id:'invoke',invoke:[{src:'foo'},{src:'bar'}],initial:'idle',states:{idle:{}}});expect(machine.root.definition.invoke).toHaveLength(2);expect(machine.root.definition.invoke.length).toEqual(native.invokeCount);});
it('materializes complete metadata without running callbacks and keeps compiled node references',()=>{let calls=0;const dynamic=()=>{calls++;return 42;},check=()=>{calls++;return true;},input=()=>{calls++;return 42;};const machine=createMachine({id:'root',version:'v1',initial:{target:'idle',actions:'initial',meta:'initial meta',description:'initial description'},description:'root description',meta:null,tags:['root-tag'],context:()=>{calls++;return {};},output:()=>{calls++;return 42;},entry:['plain',{type:'static',params:42},{type:'nil',params:null},{type:'dynamic',params:dynamic}],invoke:[{src:'foo',input,systemId:'foo-system',onDone:{target:'.done'}},{id:'inline',src:fromCallback(()=>{calls++;}),onError:{target:'.idle'},onSnapshot:[]}],states:{idle:{meta:{role:'waiting'},tags:['idle-tag'],entry:function enterIdle(){calls++;},on:{GO:{target:'done',guard:check,actions:assign(({context})=>{calls++;return context;})},BLOCKED:undefined},after:{5:'done'}},history:{type:'history',history:'deep'},done:{type:'final',output:()=>{calls++;return 'done';}}}});const d=machine.definition;expect(calls).toBe(0);expect(d).not.toBe(machine.definition);expect(d.initial.source).toBe(machine.root);expect(d.initial.target[0]).toBe(machine.states.idle);expect(d.states.idle.transitions[0].guard).toBe(check);expect(d.entry[3].params).toBe(dynamic);expect(d.invoke[0].input).toBe(input);expect(d.states.idle.on).toBe(machine.states.idle.on);expect(node(d)).toEqual(native.tree);expect(JSON.parse(JSON.stringify(d))).toEqual(native.treeJson);expect({fresh:d!==machine.definition,source:d.initial.source===machine.root,target:d.initial.target[0]===machine.states.idle,guard:d.states.idle.transitions[0].guard===check,parameters:d.entry[3].params===dynamic,input:d.invoke[0].input===input,on:d.states.idle.on===machine.states.idle.on,calls}).toEqual(native.identity);expect({meta:d.initial.meta,description:d.initial.description}).toEqual(native.initialMetadata);});
it('preserves every builtin action kind and unresolved static null dynamic params',()=>{let calls=0;const logic=fromCallback(()=>{calls++;});const explicit=()=>{calls++;};Object.defineProperty(explicit,'name',{value:'(anonymous)'});const machine=createMachine({entry:[log(),log(42),log(()=>{calls++;return 42;}),enqueueActions(()=>{calls++;}),emit({type:'notice'}),emit(()=>{calls++;return {type:'notice'};}),assign(context=>{calls++;return context;}),assign(({context})=>{calls++;return context;}),spawnChild(logic),stopChild('child'),stopChild(()=> 'child'),stopChild(()=>undefined),raise({type:'GO'}),raise(()=>({type:'GO'}),{delay:10}),raise(()=>({type:'GO'})),sendTo('child',{type:'GO'}),sendTo('child',()=>({type:'GO'}),{delay:10}),sendTo(()=>undefined,()=>({type:'GO'})),sendParent({type:'GO'}),forwardTo('child'),forwardTo(()=>undefined),cancel('timer'),cancel(()=> 'timer'),'plain',{type:'nil',params:null},{type:'dynamic',params:()=>{calls++;return 1;}},()=>{calls++;},function named(){calls++;},explicit]});expect(calls).toBe(0);expect(machine.definition.entry.map(action)).toEqual(native.actionKinds);expect(calls).toBe(0);});

it('distinguishes a forbidden transition from an empty array of candidates',()=>{const observations=[];for(const blocked of [true,false]){let calls=0;const machine=createMachine({initial:'a',on:{EV:{actions:()=>calls++}},states:{a:{on:{EV:blocked?undefined:[]}}}});const actor=createActor(machine).start();try{const definition=machine.definition.states.a,can=actor.getSnapshot().can({type:'EV'});expect(can).toBe(!blocked);actor.send({type:'EV'});expect(calls).toBe(blocked?0:1);expect(Object.hasOwn(definition.on,'EV')).toBe(blocked);expect(definition.transitions).toHaveLength(blocked?1:0);observations.push({blocked,can,calls,on:Object.hasOwn(definition.on,'EV'),transitions:definition.transitions.length});}finally{actor.stop();}}expect(observations).toEqual(native.forbidden);});

it('serializes raw and converted action forms, metadata presence and invokes without running callbacks',()=>{
 let calls=0;
 const actions=['plain',{type:'nil',params:null},{type:'static',params:{count:42}},{type:'dynamic',params:()=>{calls++;return 1;}},function work(){calls++;},assign(({context})=>{calls++;return context;})];
 const machine=createMachine({id:'json',initial:{target:'a',meta:null,actions},entry:actions,exit:actions,
  context:()=>{calls++;return {};},
  invoke:[{src:'source',input:()=>{calls++;return 1;},systemId:'system',onDone:{target:'.b'},onError:{target:'.a'},onSnapshot:[{target:['.a'],meta:null,actions:[],reenter:false},{actions}]}],
  states:{a:{on:{EV:{target:'b',actions,meta:null,description:'transition',guard:{type:'check',params:()=>{calls++;return 1;}}},PLAIN:{guard:'check'},NIL:{target:[],guard:{type:'check',params:null}},STATIC:{guard:{type:'check',params:42}},FN:{guard:()=>{calls++;return true;}}}},b:{}}});
 const json=JSON.parse(JSON.stringify(machine));expect(calls).toBe(0);expect(json).toEqual(native.metadataJson);
 expect(Object.hasOwn(json,'meta')).toBe(false);expect(json.initial.meta).toBe(null);expect(Object.hasOwn(json.initial,'reenter')).toBe(false);
 expect(json.entry[4]).toEqual({type:'work'});expect(json.states.a.on.EV[0].actions.slice(4)).toEqual([null,null]);
 expect(Object.hasOwn(json.invoke[0],'onDone')).toBe(false);expect(Object.hasOwn(json.invoke[0],'onError')).toBe(false);
});

it('serializes literal output and preserves value identity null and final-state propagation',()=>{
 const value={result:42};const machine=createMachine({initial:'a',output:value,states:{a:{type:'final',output:{something:'else'}}}});
 const actor=createActor(machine).start();try{expect(actor.getSnapshot().status).toBe('done');expect(actor.getSnapshot().output).toBe(value);expect(machine.definition.output).toBe(value);expect(JSON.parse(JSON.stringify(machine))).toEqual(native.literalJson);}finally{actor.stop();}
 let propagated;const nested=createActor(createMachine({initial:'group',states:{group:{initial:'done',states:{done:{type:'final',output:value}},onDone:{actions:({event})=>propagated=event.output}}}})).start();try{expect(propagated===value).toEqual(native.literalOutputIdentity);}finally{nested.stop();}
 const nil=createMachine({type:'final',output:null}),nilActor=createActor(nil).start();try{expect(JSON.parse(JSON.stringify(nil))).toEqual(native.literalNullJson);expect(nilActor.getSnapshot().output).toBe(null);expect(JSON.parse(JSON.stringify(nilActor.getSnapshot())).output).toBe(null);}finally{nilActor.stop();}
 const ignored=createMachine({initial:'a',states:{a:{output:value}}});expect(JSON.parse(JSON.stringify(ignored))).toEqual(native.ignoredOutputJson);
});
