import {readFileSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../../../..');
const pin=JSON.parse(readFileSync(resolve(root,'src/XState/upstream.json'),'utf8'));
const {createActor,createMachine,and,or,not}=await import(pathToFileURL(resolve(root,pin.sourceDirectory,'packages/core/src/index.ts')).href);
const {trackEntries}=await import(pathToFileURL(resolve(root,pin.sourceDirectory,'packages/core/test/utils.ts')).href);
const native=JSON.parse(readFileSync(resolve(root,'tmp/xstate-parity/csharp-guard-conditions.json'),'utf8'));
const light=(initial='green',elapsed=0)=>createMachine({context:({input={}})=>({elapsed:input.elapsed??elapsed}),initial,states:{green:{on:{TIMER:[{target:'green',guard:({context:{elapsed}})=>elapsed<100},{target:'yellow',guard:({context:{elapsed}})=>elapsed>=100&&elapsed<200}],EMERGENCY:{target:'red',guard:({event})=>!!event.isEmergency}}},yellow:{on:{TIMER:{target:'red',guard:'minTimeElapsed'},TIMER_COND_OBJ:{target:'red',guard:{type:'minTimeElapsed'}}}},red:{on:{BAD_COND:{target:'red',guard:'doesNotExist'}}}}},{guards:{minTimeElapsed:({context:{elapsed}})=>elapsed>=100&&elapsed<200}});
it('selects the first passing context condition',()=>{const machine=light();const states=[];for(const elapsed of [50,120]){const actor=createActor(machine,{input:{elapsed}}).start();try{actor.send({type:'TIMER'});expect(actor.getSnapshot().value).toBe(elapsed===50?'green':'yellow');states.push(actor.getSnapshot().value);}finally{actor.stop();}}expect(states).toEqual(native.conditions);});
for(const enabled of [true,false])it(`reads event conditions ${enabled}`,()=>{const actor=createActor(light(),{input:{}}).start();try{actor.send(enabled?{type:'EMERGENCY',isEmergency:true}:{type:'EMERGENCY'});expect(actor.getSnapshot().value).toBe(enabled?'red':'green');expect(actor.getSnapshot().value).toEqual(native['emergency:'+(enabled?'True':'False')]);}finally{actor.stop();}});
it('does not enter or exit any state when all conditions fail',()=>{const machine=createMachine({initial:'a',states:{a:{on:{TIMER:[{target:'b',guard:({event})=>event.elapsed>200},{target:'c',guard:({event})=>event.elapsed>100}]}},b:{},c:{}}});const flush=trackEntries(machine);const actor=createActor(machine).start();try{flush();actor.send({type:'TIMER',elapsed:10});const value={state:actor.getSnapshot().value,entries:flush()};expect(value).toEqual({state:'a',entries:[]});expect(value).toEqual(native.noMatch);}finally{actor.stop();}});
for(const object of [true,false])it(`resolves named guards in string and object form ${object}`,()=>{const actor=createActor(light(),{input:{elapsed:object?150:120}}).start();try{actor.send({type:'TIMER'});expect(actor.getSnapshot().value).toBe('yellow');const before=actor.getSnapshot().value;actor.send({type:object?'TIMER_COND_OBJ':'TIMER'});expect(actor.getSnapshot().value).toBe('red');expect([before,actor.getSnapshot().value]).toEqual(native['named:'+(object?'True':'False')]);}finally{actor.stop();}});
it('stays in yellow when a named guard fails',()=>{const actor=createActor(light('yellow',10)).start();try{actor.send({type:'TIMER'});expect(actor.getSnapshot().value).toBe('yellow');expect(actor.getSnapshot().value).toEqual(native.namedFalse);}finally{actor.stop();}});
it('reports the exact missing implementation error once',()=>{const errors=[];const actor=createActor(createMachine({initial:'foo',states:{foo:{on:{BAD_COND:{guard:'doesNotExist'}}}}}));actor.subscribe({error:error=>errors.push(error.message)});try{actor.start();actor.send({type:'BAD_COND'});expect(errors).toHaveLength(1);expect(errors).toEqual(native.missing);}finally{actor.stop();}});
for(const builtin of [true,false])it(`does not insert inline guards into the implementations dictionary ${builtin}`,()=>{const guards={};const machine=createMachine({on:{FOO:{guard:builtin?not(()=>false):()=>false,actions:()=>{}}}},{guards});const actor=createActor(machine).start();try{actor.send({type:'FOO'});expect(guards).toEqual({});expect(Object.keys(guards)).toEqual(native['noLeak:'+(builtin?'True':'False')]);}finally{actor.stop();}});
for(const conjunction of [true,false]){
 const key=conjunction?'True':'False';const combine=conjunction?and:or;
 for(const kind of ['inline function','string','object','nested built-in guards'])it(`${conjunction?'and':'or'} resolves ${kind}`,()=>{
  const operands=kind==='inline function'?[()=>conjunction,()=>1+1===2]:kind==='string'?[conjunction?'truthy':'falsy','truthy']:kind==='object'?[{type:'greaterThan10',params:{value:conjunction?11:4}},{type:'greaterThan10',params:{value:50}}]:[()=>conjunction,not(conjunction?'falsy':'truthy'),and([not('falsy'),'truthy'])];
  const machine=createMachine({initial:'a',states:{a:{on:{EVENT:{target:'b',guard:combine(operands)}}},b:{}}},{guards:{truthy:()=>true,falsy:()=>false,greaterThan10:(_,params)=>params.value>10}});
  const actor=createActor(machine).start();try{actor.send({type:'EVENT'});expect(actor.getSnapshot().matches('b')).toBeTruthy();expect(actor.getSnapshot().value).toEqual(native['composite:'+key+':'+kind]);}finally{actor.stop();}
 });
 it(`${conjunction?'and':'or'} resolves dynamic params`,()=>{const calls=[];const machine=createMachine({on:{EV:{guard:combine([{type:'myGuard',params:({event})=>({secret:event.secret})},()=>true]),actions:()=>{}}}},{guards:{myGuard:(_,params)=>{calls.push(params);return true;}}});const actor=createActor(machine).start();try{actor.send({type:'EV',secret:42});expect(calls).toEqual([{secret:42}]);expect(calls).toEqual(native['dynamic:'+key]);}finally{actor.stop();}});
}
