import {readFileSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../../../..');
const pin=JSON.parse(readFileSync(resolve(root,'src/XState/upstream.json'),'utf8'));
const {createActor,createMachine,fromCallback,fromPromise,assign,raise,sendParent,cancel,SimulatedClock}=await import(pathToFileURL(resolve(root,pin.sourceDirectory,'packages/core/src/index.ts')).href);
const native=JSON.parse(readFileSync(resolve(root,'tmp/xstate-parity/csharp-predictable-execution.json'),'utf8'));
const entryMachine=entry=>createMachine({context:{counter:0},initial:'a',states:{a:{on:{NEXT:'b'}},b:{entry}}});
it('executes mixed custom and assign actions in definition order',()=>{const trace=[];const actor=createActor(entryMachine([()=>trace.push('custom'),assign(()=>{trace.push('assign');return {};})])).start();try{actor.send({type:'NEXT'});expect(trace).toEqual(['custom','assign']);expect(trace).toEqual(native.mixed);}finally{actor.stop();}});
it('defers initial custom action until start',()=>{let called=false;const machine=createMachine({entry:()=>{called=true;}});expect(called).toBe(false);const before=called;const actor=createActor(machine).start();try{expect(called).toBe(true);expect([before,called]).toEqual(native.initialEffect);}finally{actor.stop();}});
it('resolves initial assign before start',()=>{const actor=createActor(createMachine({context:{called:false},entry:assign({called:true})}));try{expect(actor.getSnapshot().context.called).toBe(true);expect(actor.getSnapshot().context.called).toEqual(native.initialAssign);}finally{actor.stop();}});
for(const kind of ['custom','assign','invoke'])it(`passes raised event to ${kind}`,()=>{let eventArg;const actions=kind==='custom'?({event})=>{eventArg=event;}:kind==='assign'?assign(({event})=>{eventArg=event;return {};}):undefined;const machine=createMachine({context:{},initial:'a',states:{a:{on:{NEXT:'b'}},b:{entry:raise({type:'RAISED'}),on:{RAISED:{target:'c',actions}}},c:kind==='invoke'?{invoke:{src:fromCallback(({input})=>{eventArg=input.event;}),input:({event})=>({event})}}:{}}});const actor=createActor(machine).start();try{actor.send({type:'NEXT'});expect(eventArg.type).toBe('RAISED');expect(eventArg.type).toEqual(native['raised:'+kind]);}finally{actor.stop();}});
for(const leave of [false,true])it(`publishes children after ${leave?'exit':'entry'}`,()=>{const machine=createMachine({context:{},initial:'a',states:{a:{on:{NEXT:'b'}},b:{invoke:{id:'myChild',src:fromCallback(()=>{})},...(leave?{on:{NEXT:'c'}}:{})},...(leave?{c:{}}:{})}});const actor=createActor(machine).start();try{actor.send({type:'NEXT'});if(leave)actor.send({type:'NEXT'});expect(actor.getSnapshot().children.myChild!==undefined).toBe(!leave);expect(actor.getSnapshot().children.myChild!==undefined).toEqual(native['child:'+(leave?'True':'False')]);}finally{actor.stop();}});
it('custom action observes intermediate context between assigns',()=>{let calledWith=0;const actor=createActor(entryMachine([assign({counter:1}),({context})=>{calledWith=context.counter;},assign({counter:2})])).start();try{actor.send({type:'NEXT'});expect(calledWith).toBe(1);expect(calledWith).toEqual(native.intermediate);}finally{actor.stop();}});
it('initial actions capture only preceding context changes',()=>{const trace=[];const actor=createActor(createMachine({context:{count:0},entry:[({context})=>trace.push(context.count),assign({count:1}),({context})=>trace.push(context.count),assign({count:2}),({context})=>trace.push(context.count)]})).start();try{expect(trace).toEqual([0,1,2]);expect(trace).toEqual(native.initialContexts);}finally{actor.stop();}});
for(const occurrence of [1,2])it(`parent sees updated child snapshot before receiving child event ${occurrence}`,async()=>{const child=createMachine({initial:'a',states:{a:{after:{1:'b'}},b:{entry:sendParent({type:'CHILD_UPDATED'})}}});let actor;const machine=createMachine({invoke:{id:'myChild',src:child},initial:'initial',states:{initial:{on:{CHILD_UPDATED:[{guard:()=>actor.getSnapshot().children.myChild.getSnapshot().value==='b',target:'success'},{target:'fail'}]}},success:{type:'final'},fail:{type:'final'}}});actor=createActor(machine);const {promise,resolve,reject}=Promise.withResolvers();actor.subscribe({error:reject,complete:()=>{try{expect(actor.getSnapshot().value).toBe('success');expect(actor.getSnapshot().value).toEqual(native['updatedChild:'+occurrence]);resolve();}catch(error){reject(error);}}});try{actor.start();await promise;}finally{actor.stop();}});
it('invoke input sees context assigned by entry of the same state',async()=>{const {promise,resolve,reject}=Promise.withResolvers();const machine=createMachine({context:{updated:false},initial:'a',states:{a:{on:{NEXT:'b'}},b:{entry:assign({updated:true}),invoke:{src:fromPromise(({input})=>{try{expect(input.updated).toBe(true);expect(input.updated).toEqual(native.updatedInput);resolve();}catch(error){reject(error);}return Promise.resolve();}),input:({context})=>({updated:context.updated})}}}});const actor=createActor(machine);actor.subscribe({error:reject});try{actor.start();actor.send({type:'NEXT'});await promise;}finally{actor.stop();}});

it('static sendParent keeps identity and supports delay cancel and stop cleanup',()=>{const clock=new SimulatedClock();const ev={type:'ACK',value:42};const received=[];const child=createMachine({on:{SEND:{actions:sendParent(ev,{id:'reply',delay:10})},CANCEL:{actions:cancel('reply')}}});const actor=createActor(createMachine({invoke:{id:'child',src:child},on:{ACK:{actions:({event})=>received.push(event)}}}),{clock}).start();try{const childRef=actor.getSnapshot().children.child;childRef.send({type:'SEND'});clock.increment(9);expect(received).toHaveLength(0);clock.increment(1);expect(received).toHaveLength(1);expect(received[0]).toBe(ev);childRef.send({type:'SEND'});childRef.send({type:'CANCEL'});clock.increment(10);expect(received).toHaveLength(1);expect(clock.timeouts.size).toBe(0);childRef.send({type:'SEND'});actor.stop();clock.increment(10);expect(received).toHaveLength(1);expect({received:received.length,sameEvent:received[0]===ev,pending:clock.timeouts.size}).toEqual(native.staticParentDelay);}finally{actor.stop();}});
