import {readFileSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../../../..');
const pin=JSON.parse(readFileSync(resolve(root,'src/XState/upstream.json'),'utf8'));
const {assign,createActor,createMachine,enqueueActions,raise,sendTo,emit,fromCallback,spawnChild,stopChild}=await import(pathToFileURL(resolve(root,pin.sourceDirectory,'packages/core/src/index.ts')).href);
const native=JSON.parse(readFileSync(resolve(root,'tmp/xstate-parity/csharp-send-raise.json'),'utf8'));
for(const mode of ['actor','expression','named','reference'])it(`sends to a spawned actor using ${mode}`,()=>{const received=[];const child=createMachine({initial:'waiting',states:{waiting:{on:{EVENT:{actions:({event})=>received.push({type:event.type,count:event.count??null})}}}}});const entry=mode==='named'?sendTo('child',{type:'EVENT'}):mode==='expression'?sendTo(({context})=>context.child,({context})=>({type:'EVENT',count:context.count})):sendTo(({context})=>context.child,{type:'EVENT'});const ref=createActor(createMachine({context:({spawn})=>({child:spawn(child,['named','expression'].includes(mode)?{id:'child'}:{}),count:42}),entry})).start();try{expect(received).toEqual(native[mode]);}finally{ref.stop();}});
it('uses triggering event to resolve target',()=>{const received=[];const ref=createActor(createMachine({initial:'a',context:({spawn})=>({foo:spawn(fromCallback(({receive})=>receive(event=>{expect(event).toEqual({type:'EVENT'});received.push(event.type);}))) }),states:{a:{on:{EVENT:{actions:sendTo(({context,event})=>context[event.value],{type:'EVENT'})}}}}})).start();try{ref.send({type:'EVENT',value:'foo'});expect(received).toEqual(native.eventTarget);}finally{ref.stop();}});
for(const raised of [false,true])it(`rejects string events during ${raised?'raise':'sendTo'} resolution`,()=>{const config=raised?{entry:raise('a string')}:{invoke:{id:'child',src:fromCallback(()=>{})},entry:sendTo('child','a string')};const ref=createActor(createMachine(config));const errors=[];ref.subscribe({error:error=>errors.push(error.message)});try{ref.start();expect(errors).toEqual([native['invalid:'+(raised?'raise':'sendTo')]]);}finally{ref.stop();}});
it('sees committed context in self-event handler',()=>{const captured=[];const ref=createActor(createMachine({context:{counter:0},initial:'a',states:{a:{on:{NEXT:'b'}},b:{entry:[assign({counter:1}),sendTo(({self})=>self,{type:'EVENT'})],on:{EVENT:{target:'c',actions:({self})=>captured.push(self.getSnapshot().context.counter)}}},c:{}}})).start();try{ref.send({type:'NEXT'});ref.send({type:'EVENT'});expect(captured).toEqual(native.selfSnapshot);}finally{ref.stop();}});
for(const invoke of [false,true])it(`delivers delayed event to the stopped ${invoke?'invoked':'spawned'} instance rather than replacement ID`,async()=>{
 const warnings=[];const warn=vi.spyOn(console,'warn').mockImplementation(value=>warnings.push(value));let calls1=0,calls2=0;const ids=[];const child1=createMachine({on:{PING:{actions:()=>calls1++}}});const child2=createMachine({on:{PING:{actions:()=>calls2++}}});const send=sendTo('myChild',{type:'PING'},{delay:1});const states={a:{on:{START:'b'}}};if(invoke){states.b={entry:send,invoke:{src:'child1',id:'myChild'},on:{NEXT:'c'}};states.c={invoke:{src:'child2',id:'myChild'}};}else states.b={entry:[spawnChild('child1',{id:'myChild'}),send,stopChild('myChild'),spawnChild('child2',{id:'myChild'})]};
 const ref=createActor(createMachine({initial:'a',states},{actors:{child1,child2}}),{inspect:event=>{if(event.type==='@xstate.actor'&&event.actorRef.id==='myChild')ids.push(event.actorRef.sessionId);}});
 try{ref.start();ref.send({type:'START'});if(invoke)ref.send({type:'NEXT'});await new Promise(resolve=>setTimeout(resolve,10));expect(ids).toHaveLength(2);expect(warnings).toHaveLength(1);expect(warnings[0]).toContain(`myChild (${ids[0]})`);expect({calls1,calls2,warnings:warnings.map(value=>value.replace(ids[0],'<stopped>'))}).toEqual(native[invoke?'replacedInvoke':'replacedSpawn']);}finally{ref.stop();warn.mockRestore();}
});
it('raises static event in the entered state',()=>{const ref=createActor(createMachine({initial:'a',states:{a:{entry:raise({type:'TO_B'}),on:{TO_B:'b'}},b:{type:'final'}}})).start();try{expect(ref.getSnapshot().value).toEqual(native.raiseStatic);}finally{ref.stop();}});
for(const context of [false,true])it(`raises computed event ${context}`,()=>{const ref=createActor(createMachine({context:{eventType:'RAISED'},initial:'a',states:{a:{on:{NEXT:{actions:raise(({context:current})=>({type:context?current.eventType:'RAISED'}))},RAISED:'b'}},b:{}}})).start();try{ref.send({type:'NEXT'});expect(ref.getSnapshot().value).toEqual(native[context?'raiseContext':'raiseExpression']);}finally{ref.stop();}});
